name: match_chewBBACA_to_Enterobase

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      # Install tree using apt to check github repo structure
      - name: apt
        run: sudo apt-get install --no-install-recommends tree
      # Install pandas using conda
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env_python
          environment-file: envs/python.yml
          python-version: 3.8
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - uses: actions/checkout@v2
        with:
          repository: boasvdp/match_chewBBACA_to_Enterobase
          path: match_chewBBACA_to_Enterobase
      - name: directory structure
        run: tree -d $GITHUB_WORKSPACE
      - name: check active conda env
        run: echo "Current conda env is $CONDA_DEFAULT_ENV" 
      - name: test match_chewBBACA_to_Enterobase
        run: |
         # Cd into checked out github repo
         cd $GITHUB_WORKSPACE/match_chewBBACA_to_Enterobase

         # Make script executable and activate conda env
         chmod u+x ./match_chewBBACA_to_Enterobase.py

         # Check basic functionality
         ! ./match_chewBBACA_to_Enterobase.py
         ./match_chewBBACA_to_Enterobase.py --help

         # Run script on test files
         ./match_chewBBACA_to_Enterobase.py --profiles test/profiles.tsv --input test/input.tsv --st-to-hiercc test/ST_to_HierCC.tsv --output test.csv
         diff -q test/correct.csv test.csv
